import {
  TRANSCRIPT_SOURCES,
  type TranscriptDocument,
  type TranscriptDocumentInput,
  type TranscriptSegment,
  type TranscriptSource,
} from "./types";

export type TranscriptDomainErrorCode =
  | "INVALID_VIDEO_ID"
  | "INVALID_LANGUAGE_CODE"
  | "INVALID_TRANSCRIPT_SOURCE"
  | "EMPTY_TRANSCRIPT"
  | "INVALID_SEGMENT_START"
  | "INVALID_SEGMENT_DURATION"
  | "EMPTY_SEGMENT_TEXT"
  | "UNSORTED_SEGMENTS";

export class TranscriptDomainError extends Error {
  readonly code: TranscriptDomainErrorCode;

  constructor(code: TranscriptDomainErrorCode, message: string) {
    super(message);
    this.name = "TranscriptDomainError";
    this.code = code;
  }
}

function isTranscriptSource(source: string): source is TranscriptSource {
  return TRANSCRIPT_SOURCES.some((allowedSource) => allowedSource === source);
}

export function createTranscriptDocument(input: TranscriptDocumentInput): TranscriptDocument {
  const videoId = input.videoId.trim();
  if (videoId.length === 0) {
    throw new TranscriptDomainError("INVALID_VIDEO_ID", "videoId must be a non-empty string");
  }

  const languageCode = input.languageCode.trim();
  if (languageCode.length === 0) {
    throw new TranscriptDomainError(
      "INVALID_LANGUAGE_CODE",
      "languageCode must be a non-empty string",
    );
  }

  if (!isTranscriptSource(input.source)) {
    throw new TranscriptDomainError(
      "INVALID_TRANSCRIPT_SOURCE",
      "Transcript source is not supported",
    );
  }

  if (input.segments.length === 0) {
    throw new TranscriptDomainError("EMPTY_TRANSCRIPT", "Transcript must contain a segment");
  }

  const segments: TranscriptSegment[] = [];
  let previousStartSeconds = 0;

  for (const [index, inputSegment] of input.segments.entries()) {
    if (!Number.isFinite(inputSegment.startSeconds) || inputSegment.startSeconds < 0) {
      throw new TranscriptDomainError(
        "INVALID_SEGMENT_START",
        `Segment ${index} has an invalid startSeconds`,
      );
    }

    if (!Number.isFinite(inputSegment.durationSeconds) || inputSegment.durationSeconds < 0) {
      throw new TranscriptDomainError(
        "INVALID_SEGMENT_DURATION",
        `Segment ${index} has an invalid durationSeconds`,
      );
    }

    const derivedEndSeconds = inputSegment.startSeconds + inputSegment.durationSeconds;
    if (!Number.isFinite(derivedEndSeconds)) {
      throw new TranscriptDomainError(
        "INVALID_SEGMENT_DURATION",
        `Segment ${index} produces a non-finite end time`,
      );
    }

    const text = inputSegment.text.trim();
    if (text.length === 0) {
      throw new TranscriptDomainError(
        "EMPTY_SEGMENT_TEXT",
        `Segment ${index} must contain non-empty text`,
      );
    }

    if (index > 0 && inputSegment.startSeconds < previousStartSeconds) {
      throw new TranscriptDomainError(
        "UNSORTED_SEGMENTS",
        `Segment ${index} starts before the previous segment`,
      );
    }

    segments.push(
      Object.freeze({
        index,
        startSeconds: inputSegment.startSeconds,
        durationSeconds: inputSegment.durationSeconds,
        text,
      }),
    );
    previousStartSeconds = inputSegment.startSeconds;
  }

  return Object.freeze({
    videoId,
    languageCode,
    source: input.source,
    isAutoGenerated: input.isAutoGenerated,
    segments: Object.freeze(segments),
  });
}

export function getTranscriptSegmentEndSeconds(segment: TranscriptSegment): number {
  return segment.startSeconds + segment.durationSeconds;
}

export function getTranscriptDurationSeconds(document: TranscriptDocument): number {
  let maximumEndSeconds = 0;
  for (const segment of document.segments) {
    maximumEndSeconds = Math.max(maximumEndSeconds, getTranscriptSegmentEndSeconds(segment));
  }
  return maximumEndSeconds;
}

export function getTranscriptPlainText(document: TranscriptDocument): string {
  return document.segments.map((segment) => segment.text).join(" ");
}
