export const TRANSCRIPT_SOURCES = Object.freeze([
  "youtube-captions",
  "manual",
  "audio-transcription",
] as const);

export type TranscriptSource = (typeof TRANSCRIPT_SOURCES)[number];

export interface TranscriptSegmentInput {
  readonly startSeconds: number;
  readonly durationSeconds: number;
  readonly text: string;
}

export interface TranscriptSegment {
  readonly index: number;
  readonly startSeconds: number;
  readonly durationSeconds: number;
  readonly text: string;
}

export interface TranscriptDocumentInput {
  readonly videoId: string;
  readonly languageCode: string;
  readonly source: TranscriptSource;
  readonly isAutoGenerated: boolean;
  readonly segments: readonly TranscriptSegmentInput[];
}

export interface TranscriptDocument {
  readonly videoId: string;
  readonly languageCode: string;
  readonly source: TranscriptSource;
  readonly isAutoGenerated: boolean;
  readonly segments: readonly TranscriptSegment[];
}
